CREATE USER 'rebood_workshop'@'%' IDENTIFIED BY 'WG4NqWzrWgsLtnlI';
GRANT USAGE ON *.* TO 'rebood_workshop'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `rebood_workshop`;
GRANT ALL PRIVILEGES ON `rebood\_workshop`.* TO 'rebood_workshop'@'%';
