apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
data:
  user: {{ .Values.db.user | b64enc }}
  password: {{ .Values.db.password | b64enc }}
  name: {{ .Values.db.name | b64enc }}
