apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.svc" . }}
  labels:
    app: {{ template "app.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: http
    port: {{ .Values.app.service.externalPort }}
    targetPort: {{ .Values.app.service.internalPort }}
  selector:
    app: {{ template "app.fullname" . }}
