{{- if .Values.autoscaler.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "app.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "app.fullname" . }}
  minReplicas: {{ .Values.replicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaler.targetCPUUtilizationPercentage }}
{{- end }}
