repo: "vaclavdvorak2vd"
project: "rebood-devops-workshop" # Docker image name
dockerTag: "latest" # Docker image tag
env: "dev"  # Environment name
replicas: 1
imagePullPolicy: Always
gitRevision: %GIT_REVISION%

app:
  service:
    name: app
    externalPort: 80
    internalPort: 8080
  resources:
    requests:
      memory: 64Mi
      cpu: 10m
    limits:
      cpu: 250m
      memory: 512Mi

db:
  image: "mariadb:10.2"
  port: 3306
  user: "foo"
  password: "bar"
  name: "baz"
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    size: 1Gi

ingress:
  enabled: true
  # Used to create an Ingress record.
  annotations:
    kubernetes.io/tls-acme: true
  hosts:
   - "example.com"
  path: /
